In [32]:
import tensorflow as tf

In [33]:
print(tf.__version__)

1.14.0


In [34]:
hello = tf.constant("Hello ")

In [35]:
world = tf.constant("World")

In [36]:
print(hello)

Tensor("Const_6:0", shape=(), dtype=string)


In [37]:
with tf.Session() as sess:
    result = sess.run(hello + world)

In [38]:
print(result)

b'Hello World'


In [39]:
a = tf.constant(10)

In [40]:
b = tf.constant(20)

In [41]:
a +b

<tf.Tensor 'add_6:0' shape=() dtype=int32>

In [42]:

a +b

<tf.Tensor 'add_7:0' shape=() dtype=int32>

In [43]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [44]:
result

30

In [45]:
const = tf.constant(10)

In [46]:
fill_mat = tf.fill((4,4),10)

In [47]:
myzeros = tf.zeros((4,4))

In [48]:
myones = tf.ones((4,4))

In [49]:
myrandn = tf.random_normal((4,4), mean=0,stddev=1.0)

In [50]:
myrandu = tf.random_uniform((4,4), minval=0, maxval=1)

In [52]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [53]:
sess = tf.InteractiveSession()

In [55]:
for op in my_ops:
    print(sess.run(op))
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 0.92675436  0.20374997  0.19684401 -1.3045602 ]
 [ 0.28049663  0.00400598  0.66477454  2.856777  ]
 [-0.10691675  0.73008156  0.9046168  -0.4122238 ]
 [-0.5009469   0.9464     -0.44843584  1.0037973 ]]


[[0.59994924 0.658939   0.24641407 0.27315664]
 [0.07379401 0.5093007  0.5968461  0.19599116]
 [0.7047801  0.2807318  0.893224   0.9051807 ]
 [0.36711228 0.36583114 0.41359305 0.83019733]]




In [56]:
for op in my_ops:
    print(op.eval())
    print('\n')

10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[ 1.0558249  -0.78836125 -0.4830936  -0.3768476 ]
 [-0.614088   -0.35835484 -0.4879721  -0.15083079]
 [ 2.567288    1.3133986   0.1243143   0.52885896]
 [ 1.0693859  -0.62381697 -0.61386013  0.8378725 ]]


[[0.96985066 0.76624966 0.5576403  0.04062331]
 [0.07152224 0.3551557  0.58710563 0.95006466]
 [0.9269388  0.21944809 0.79086065 0.7546383 ]
 [0.27032375 0.5881038  0.59184754 0.30613804]]




In [57]:
a = tf.constant([[1,2],
                [3,4]])

In [58]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [61]:
b = tf.constant([[10],[100]])

In [62]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [63]:
result = tf.matmul(a,b)

In [64]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [65]:
result.eval()

array([[210],
       [430]], dtype=int32)